{
 "title": "Clients",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(client_e2e_latency, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "AVG p50 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(client_e2e_latency{percentile=\"50\",instance=~\"$node\"}[$__interval]))\n/\n    sum(count_over_time(client_e2e_latency{percentile=\"50\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AVG p75 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(client_e2e_latency{percentile=\"75\",instance=~\"$node\"}[$__interval]))\n/\n    sum(count_over_time(client_e2e_latency{percentile=\"75\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AVG p95 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(client_e2e_latency{percentile=\"95\",instance=~\"$node\"}[$__interval]))\n/\n    sum(count_over_time(client_e2e_latency{percentile=\"95\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAX p50 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(max_over_time(client_e2e_latency{percentile=\"50\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAX p75 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "max(max_over_time(client_e2e_latency{percentile=\"75\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAX p95 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "max(max_over_time(client_e2e_latency{percentile=\"95\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AVG p99 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(sum_over_time(client_e2e_latency{percentile=\"99\",instance=~\"$node\"}[$__interval]))\n/\n    sum(count_over_time(client_e2e_latency{percentile=\"99\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AVG p99.9 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "sum(sum_over_time(client_e2e_latency{percentile=\"99.9\",instance=~\"$node\"}[$__interval]))\n/\n    sum(count_over_time(client_e2e_latency{percentile=\"99.9\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AVG p99.99 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum(sum_over_time(client_e2e_latency{percentile=\"99.99\",instance=~\"$node\"}[$__interval]))\n/\n    sum(count_over_time(client_e2e_latency{percentile=\"99.99\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAX p99 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "max(max_over_time(client_e2e_latency{percentile=\"99\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAX p99.9 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "max(max_over_time(client_e2e_latency{percentile=\"99.9\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAX p99.99 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "targets": [
    {
     "expr": "max(max_over_time(client_e2e_latency{percentile=\"99.99\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AVG p99.999 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 6 },
   "targets": [
    {
     "expr": "sum(sum_over_time(client_e2e_latency{percentile=\"99.999\",instance=~\"$node\"}[$__interval]))\n/\n    sum(count_over_time(client_e2e_latency{percentile=\"99.999\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AVG p100 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(sum_over_time(client_e2e_latency{percentile=\"100\",instance=~\"$node\"}[$__interval]))\n/\n    sum(count_over_time(client_e2e_latency{percentile=\"100\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAX p99.999 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "max(max_over_time(client_e2e_latency{percentile=\"99.999\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAX p100 e2e lat ms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "max(max_over_time(client_e2e_latency{percentile=\"100\",instance=~\"$node\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - p50",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"50\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - p75",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"75\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - p90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"90\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"95\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"99\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - p99.9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"99.9\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - p99.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"99.99\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - p99.999",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"99.999\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end latency - Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "client_e2e_latency{percentile=\"100\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}